# Generated by Django 5.2.3 on 2025-07-04 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=20)),
                ('service', models.CharField(choices=[('AI & ML Development', 'AI & ML Development'), ('Web & Mobile Apps', 'Web & Mobile Apps'), ('Backup Solutions', 'Backup Solutions'), ('Custom Software', 'Custom Software'), ('Cloud Solutions', 'Cloud Solutions'), ('Cybersecurity', 'Cybersecurity')], max_length=50)),
                ('message', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
