# Generated by Django 5.2.3 on 2025-06-15 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='JobOpening',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('experience', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('apply_link', models.URLField()),
                ('is_active', models.BooleanField(default=True)),
                ('posted_on', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
