# Generated by Django 5.2.3 on 2025-06-26 23:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reselling', '0002_testimonial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeCTA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heading', models.CharField(max_length=200)),
                ('subtext', models.TextField(blank=True)),
                ('button_text', models.CharField(default='Contact Us', max_length=100)),
                ('button_url', models.URLField(default='/contact/')),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
    ]
